### ISSUE TITLE
Creating Ubuntu boxes broke down

### ISSUE THREAD

**Issue by Blaisorblade** [kraksoft/vagrant-box#3]
The 14.04 image is no more available at the original URL. I tried updating to 14.04.2, and run into more problems due to the Ubuntu changes and more. In retrospect, an easier fix might have been changing the URL to point to the same file somewhere else (if I find a reasonable location).

For current info on updating to 14.04.2, for now see commits at my fork:

https://github.com/Blaisorblade/vagrant-box/tree/topic/extract-xorriso
https://github.com/Blaisorblade/vagrant-box/tree/topic/ub-update

**Comment by kedrap** [comment]
I've updated links for Debian and Ubuntu, and now, all tags should works.

**Comment by Blaisorblade** [comment]
Right, I guess so as well (haven't double-checked).
