### ISSUE TITLE
7zip and >= 64 characters filenames.

### ISSUE THREAD

**Issue by Blaisorblade** [kraksoft/vagrant-box#6]
One problem with 14.04.2 (that appeared in #5) potentially remains: 7zip will not extract correctly filenames longer than 64 characters, and this can break the installation. It seems luck that this didn't affect 14.04 and other releases —simply because version names of packages were shorter.

That's of course 7zip's fault, but I thought I'd at least note this down in case this ever becomes relevant again.

I'd fix this right away, but I didn't find yet a good multi-platform replacement for 7zip.

Feel free to close if you don't want to fix this for now.

**Comment by kedrap** [comment]
Because we have fixed urls to previous Debian and Ubuntu version, I close the issue.

Let's reopen this issue, when problem with 7zip occurs in the future. 
Currently, I haven't idea for a good and well known replacement for 7zip.
